version: '2'

services:
  gitlabsvgbadges:
    build: .
#        ports:
#        - "80:80"
    restart: always
    labels:
      - "traefik.backend=gitlabsvgbadges"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:gitlabsvgbadges.docker.lab"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=false"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
