version: '2'

services:
  gitlabsvgbadges:
    build: .
#        ports:
#        - "80:80"
    restart: unless-stopped
    volumes:
      - ./trustedCerts=/var/www/apache-flask/trustedCerts
    env_file:
      - environment.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlabsvgbadges.rule=Host(`gitlabsvgbadges.docker.lab`)"
      - "traefik.http.services.gitlabsvgbadges.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_proxy"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
